/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

operandos *
suma_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

operandos *
restar_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	restar_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, restar, (xdrproc_t) xdr_restar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

operandos *
multiplica_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	multiplica_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, multiplica, (xdrproc_t) xdr_multiplica_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

operandos *
divide_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	divide_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, divide, (xdrproc_t) xdr_divide_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

operandos *
producto_escalar_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	producto_escalar_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, producto_escalar, (xdrproc_t) xdr_producto_escalar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

operandos *
producto_vectorial_1(operandos op1, operandos op2,  CLIENT *clnt)
{
	producto_vectorial_1_argument arg;
	static operandos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.op1 = op1;
	arg.op2 = op2;
	if (clnt_call (clnt, producto_vectorial, (xdrproc_t) xdr_producto_vectorial_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_operandos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
