/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void print_operandos(operandos op){
	printf("Len de la solucion: %d\n",op.values.values_len);
	for(int i = 0; i < op.values.values_len;i++){
		printf("%f ",op.values.values_val[i]);
	}
	printf("\n");
}

operandos *
suma_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);
	if (op1.values.values_len != op2.values.values_len) {
		fprintf(stderr, "Error: los elementos tienen diferentes longitudes\n");
		result.values.values_val = NULL;
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_val = (double* )malloc(sizeof(double)*(op1.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op1.values.values_len;
	
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	

	printf("\n");

	for(int i = 0; i < op1.values.values_len; i++){
		result.values.values_val[i] = op1.values.values_val[i] + op2.values.values_val[i];	
	}

	printf("Solucion de la suma en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}

operandos *
restar_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);
	if (op1.values.values_len != op2.values.values_len) {
		fprintf(stderr, "Error: los elementos tienen diferentes longitudes\n");
		result.values.values_val = NULL;
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_val = (double* )malloc(sizeof(double)*(op1.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op1.values.values_len;
	/*
	printf("Result len: %d\n", result.values.values_len);
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	*/
	printf("\n");

	for(int i = 0; i < op1.values.values_len; i++){
		result.values.values_val[i] = op1.values.values_val[i] - op2.values.values_val[i];	
	}

	printf("Solucion de la resta en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}

operandos *
multiplica_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);
	if (op1.values.values_len != op2.values.values_len) {
		fprintf(stderr, "Error: los elementos tienen diferentes longitudes\n");
		result.values.values_val = NULL;
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_val = (double* )malloc(sizeof(double)*(op1.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op1.values.values_len;
	
	printf("Result len: %d\n", result.values.values_len);
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	
	printf("\n");

	for(int i = 0; i < op1.values.values_len; i++){
		result.values.values_val[i] = op1.values.values_val[i] * op2.values.values_val[i];	
	}

	printf("Solucion de la multiplicacion en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}

operandos *
divide_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);
	if (op1.values.values_len != op2.values.values_len) {
		fprintf(stderr, "Error: los elementos tienen diferentes longitudes\n");
		result.values.values_val = NULL;
		result.values.values_len = -1;
		return &result;
	}

	for(int i = 0; i < op2.values.values_len; i++){
		if(op2.values.values_val[i] == 0.0){
			printf("No se puede divir entre 0\n");
			return &result;
		}
	}

	result.values.values_val = (double* )malloc(sizeof(double)*(op1.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op1.values.values_len;
	/*
	printf("Result len: %d\n", result.values.values_len);
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	*/

	printf("\n");

	for(int i = 0; i < op1.values.values_len; i++){
		result.values.values_val[i] = op1.values.values_val[i] / op2.values.values_val[i];	
	}

	printf("Solucion de la division en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}

operandos *
producto_escalar_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);

	result.values.values_val = (double* )malloc(sizeof(double)*(op2.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op2.values.values_len;
	/*
	printf("Result len: %d\n", result.values.values_len);
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	*/

	printf("\n");

	for(int i = 0; i < op2.values.values_len; i++){
		result.values.values_val[i] = op1.values.values_val[0] * op2.values.values_val[i];	
	}

	printf("Solucion del producto escalar en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}

operandos *
producto_vectorial_1_svc(operandos op1, operandos op2,  struct svc_req *rqstp)
{
	static operandos result;

	xdr_free(xdr_operandos, &result);
	printf("-> Recibiendo del cliente \n");
	printf("Operandos 1\n");
	print_operandos(op1);
	printf("Operandos 2\n");
	print_operandos(op2);
	//Para producto vectorial solo tiene sentido que los vectores sean de 3 elementos
	if ((op1.values.values_len != op2.values.values_len) || (op1.values.values_len !=  3) || (op2.values.values_len != 3)) {
		fprintf(stderr, "Error: los elementos tienen longitudes erroneas\n");
		result.values.values_val = NULL;
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_val = (double* )malloc(sizeof(double)*(op2.values.values_len+1));
	if (result.values.values_val == NULL) {
		fprintf(stderr, "Error: fallo al reservar memoria\n");
		result.values.values_len = -1;
		return &result;
	}

	result.values.values_len = op2.values.values_len;
	
	printf("Result len: %d\n", result.values.values_len);
	
	

	printf("\n");

	result.values.values_val[0] = op1.values.values_val[1] * op2.values.values_val[2] - op1.values.values_val[2] * op2.values.values_val[1];
    result.values.values_val[1] = op1.values.values_val[2] * op2.values.values_val[0] - op1.values.values_val[0] * op2.values.values_val[2];
    result.values.values_val[2] = op1.values.values_val[0] * op2.values.values_val[1] - op1.values.values_val[1] * op2.values.values_val[0];
	

	printf("Solucion del cross product en el server: \n");
	print_operandos(result);
	printf("\n---------------------------------------------------------\n");
	
	return &result;
}